name: repoworker

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
  workflow_dispatch: null

jobs:
  update_shards:
    name: update repodata shards
    runs-on: "ubuntu-latest"
    steps:
      - name: skip me
        shell: bash -l {0}
        if: success() && contains(github.event.head_commit.message, 'ci skip')
        run: |
          echo "commit message: '${MSG}'"
          echo "::set-env name=CI_SKIP::true"
        env:
          MSG: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v2
        if: success() && ! env.CI_SKIP

      - uses: goanpeca/setup-miniconda@v1
        if: success() && ! env.CI_SKIP
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: stop me if needed
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP
        run: |
          conda install git -y -q
          python stop_me_if_needed.py

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        if: success() && ! env.CI_SKIP
        with:
          access_token: ${{ secrets.MY_PAT }}

      - name: make repodata
        if: success() && ! env.CI_SKIP
        shell: bash -l {0}
        run: |
          conda install -y -q git
          git config --global user.name 'conda-forge-daemon'
          git config --global user.email '64793534+conda-forge-daemon@users.noreply.github.com'
          git config --global pull.rebase false

          pushd ..
          git clone https://github.com/regro/repodata-tools.git
          pushd repodata-tools
          conda install -y -q --file requirements.txt
          pip install -e .
          popd
          popd

          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            run-repodata-worker --make-releases --main-only 7710
          else
            run-repodata-worker 300
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

      - name: stop me if needed
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP
        run: |
          conda install git -y -q
          python stop_me_if_needed.py

      - name: trigger next job
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: repoworker
          token: ${{ secrets.MY_PAT }}
        if: github.ref == 'refs/heads/master' && ! env.CI_SKIP
