name: start

on:
  push:
    branches:
      - master

jobs:
  start:
    name: start
    runs-on: "ubuntu-latest"
    steps:
      - name: skip me
        shell: bash -l {0}
        if: success() && contains(github.event.head_commit.message, 'ci skip')
        run: |
          echo "commit message: '${MSG}'"
          echo "::set-env name=CI_SKIP::true"
        env:
          MSG: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v2
        if: success() && ! env.CI_SKIP

      - uses: goanpeca/setup-miniconda@v1
        if: success() && ! env.CI_SKIP
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: stop me if needed
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP
        run: |
          conda install git -y -q
          python stop_me_if_needed.py

      - name: trigger worker
        uses: benc-uk/workflow-dispatch@v1
        if: github.ref == 'refs/heads/master' && ! cancelled() && ! failure() && ! env.CI_SKIP
        with:
          workflow: repoworker
          token: ${{ secrets.MY_PAT }}
