name: repoworker

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
  push:
    branches:
      - master
  workflow_dispatch: null

jobs:
  update_shards:
    name: update repodata shards
    runs-on: "ubuntu-latest"
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.MY_PAT }}

      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: make repodata
        shell: bash -l {0}
        run: |
          conda install -y -q git

          pushd ..
          git clone https://github.com/regro/repodata-tools.git
          pushd repodata-tools
          git checkout repoworker
          conda install -y -q --file requirements.txt
          pip install -e .
          popd
          popd

          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            run-repodata-worker --make-releases --main-only 18000
          else
            run-repodata-worker 300
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

      - name: trigger next job
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: repoworker
          token: ${{ secrets.MY_PAT }}
        if: github.ref == 'refs/heads/master'
